# CMake generated Testfile for 
# Source directory: C:/projects/emwave-c/tests/unit
# Build directory: C:/projects/emwave-c/build-imgui/tests/unit
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[config_loader_tests]=] "C:/projects/emwave-c/build-imgui/tests/unit/Debug/config_loader_tests.exe")
  set_tests_properties([=[config_loader_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/projects/emwave-c/tests/unit/CMakeLists.txt;26;add_test;C:/projects/emwave-c/tests/unit/CMakeLists.txt;29;add_emwave_check_test;C:/projects/emwave-c/tests/unit/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[config_loader_tests]=] "C:/projects/emwave-c/build-imgui/tests/unit/Release/config_loader_tests.exe")
  set_tests_properties([=[config_loader_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/projects/emwave-c/tests/unit/CMakeLists.txt;26;add_test;C:/projects/emwave-c/tests/unit/CMakeLists.txt;29;add_emwave_check_test;C:/projects/emwave-c/tests/unit/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[config_loader_tests]=] "C:/projects/emwave-c/build-imgui/tests/unit/MinSizeRel/config_loader_tests.exe")
  set_tests_properties([=[config_loader_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/projects/emwave-c/tests/unit/CMakeLists.txt;26;add_test;C:/projects/emwave-c/tests/unit/CMakeLists.txt;29;add_emwave_check_test;C:/projects/emwave-c/tests/unit/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[config_loader_tests]=] "C:/projects/emwave-c/build-imgui/tests/unit/RelWithDebInfo/config_loader_tests.exe")
  set_tests_properties([=[config_loader_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/projects/emwave-c/tests/unit/CMakeLists.txt;26;add_test;C:/projects/emwave-c/tests/unit/CMakeLists.txt;29;add_emwave_check_test;C:/projects/emwave-c/tests/unit/CMakeLists.txt;0;")
else()
  add_test([=[config_loader_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[fdtd_core_tests]=] "C:/projects/emwave-c/build-imgui/tests/unit/Debug/fdtd_core_tests.exe")
  set_tests_properties([=[fdtd_core_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/projects/emwave-c/tests/unit/CMakeLists.txt;26;add_test;C:/projects/emwave-c/tests/unit/CMakeLists.txt;34;add_emwave_check_test;C:/projects/emwave-c/tests/unit/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[fdtd_core_tests]=] "C:/projects/emwave-c/build-imgui/tests/unit/Release/fdtd_core_tests.exe")
  set_tests_properties([=[fdtd_core_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/projects/emwave-c/tests/unit/CMakeLists.txt;26;add_test;C:/projects/emwave-c/tests/unit/CMakeLists.txt;34;add_emwave_check_test;C:/projects/emwave-c/tests/unit/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[fdtd_core_tests]=] "C:/projects/emwave-c/build-imgui/tests/unit/MinSizeRel/fdtd_core_tests.exe")
  set_tests_properties([=[fdtd_core_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/projects/emwave-c/tests/unit/CMakeLists.txt;26;add_test;C:/projects/emwave-c/tests/unit/CMakeLists.txt;34;add_emwave_check_test;C:/projects/emwave-c/tests/unit/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[fdtd_core_tests]=] "C:/projects/emwave-c/build-imgui/tests/unit/RelWithDebInfo/fdtd_core_tests.exe")
  set_tests_properties([=[fdtd_core_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/projects/emwave-c/tests/unit/CMakeLists.txt;26;add_test;C:/projects/emwave-c/tests/unit/CMakeLists.txt;34;add_emwave_check_test;C:/projects/emwave-c/tests/unit/CMakeLists.txt;0;")
else()
  add_test([=[fdtd_core_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[analysis_tests]=] "C:/projects/emwave-c/build-imgui/tests/unit/Debug/analysis_tests.exe")
  set_tests_properties([=[analysis_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/projects/emwave-c/tests/unit/CMakeLists.txt;26;add_test;C:/projects/emwave-c/tests/unit/CMakeLists.txt;36;add_emwave_check_test;C:/projects/emwave-c/tests/unit/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[analysis_tests]=] "C:/projects/emwave-c/build-imgui/tests/unit/Release/analysis_tests.exe")
  set_tests_properties([=[analysis_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/projects/emwave-c/tests/unit/CMakeLists.txt;26;add_test;C:/projects/emwave-c/tests/unit/CMakeLists.txt;36;add_emwave_check_test;C:/projects/emwave-c/tests/unit/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[analysis_tests]=] "C:/projects/emwave-c/build-imgui/tests/unit/MinSizeRel/analysis_tests.exe")
  set_tests_properties([=[analysis_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/projects/emwave-c/tests/unit/CMakeLists.txt;26;add_test;C:/projects/emwave-c/tests/unit/CMakeLists.txt;36;add_emwave_check_test;C:/projects/emwave-c/tests/unit/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[analysis_tests]=] "C:/projects/emwave-c/build-imgui/tests/unit/RelWithDebInfo/analysis_tests.exe")
  set_tests_properties([=[analysis_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/projects/emwave-c/tests/unit/CMakeLists.txt;26;add_test;C:/projects/emwave-c/tests/unit/CMakeLists.txt;36;add_emwave_check_test;C:/projects/emwave-c/tests/unit/CMakeLists.txt;0;")
else()
  add_test([=[analysis_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[config_runtime_tests]=] "C:/projects/emwave-c/build-imgui/tests/unit/Debug/config_runtime_tests.exe")
  set_tests_properties([=[config_runtime_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/projects/emwave-c/tests/unit/CMakeLists.txt;26;add_test;C:/projects/emwave-c/tests/unit/CMakeLists.txt;38;add_emwave_check_test;C:/projects/emwave-c/tests/unit/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[config_runtime_tests]=] "C:/projects/emwave-c/build-imgui/tests/unit/Release/config_runtime_tests.exe")
  set_tests_properties([=[config_runtime_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/projects/emwave-c/tests/unit/CMakeLists.txt;26;add_test;C:/projects/emwave-c/tests/unit/CMakeLists.txt;38;add_emwave_check_test;C:/projects/emwave-c/tests/unit/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[config_runtime_tests]=] "C:/projects/emwave-c/build-imgui/tests/unit/MinSizeRel/config_runtime_tests.exe")
  set_tests_properties([=[config_runtime_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/projects/emwave-c/tests/unit/CMakeLists.txt;26;add_test;C:/projects/emwave-c/tests/unit/CMakeLists.txt;38;add_emwave_check_test;C:/projects/emwave-c/tests/unit/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[config_runtime_tests]=] "C:/projects/emwave-c/build-imgui/tests/unit/RelWithDebInfo/config_runtime_tests.exe")
  set_tests_properties([=[config_runtime_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/projects/emwave-c/tests/unit/CMakeLists.txt;26;add_test;C:/projects/emwave-c/tests/unit/CMakeLists.txt;38;add_emwave_check_test;C:/projects/emwave-c/tests/unit/CMakeLists.txt;0;")
else()
  add_test([=[config_runtime_tests]=] NOT_AVAILABLE)
endif()
